# Generated by Django 3.2.9 on 2021-12-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=150)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracking.user')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=150)),
                ('priority', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_issue', to='issue_tracking.user')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_issue', to='issue_tracking.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracking.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('role', models.CharField(max_length=150)),
                ('user_id', models.ManyToManyField(to='issue_tracking.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracking.user')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracking.issue')),
            ],
        ),
    ]
